export const TYPES = {
  GET_ALL: 'GET_ALL',
  SAVE_ORDER: 'SAVE_ORDER',
  CANCEL_ORDER: 'CANCEL_ORDER',
  SET_ITEM: 'SET_ITEM',
  DELETE_ITEM: 'DELETE_ITEM',
  DELETE_PRODUCT: 'DELETE_PRODUCT',
  ADD_PRODUCT: 'ADD_PRODUCT',
  SET_USERNAME: 'SET_USERNAME',
  INITIAL_STATE: 'INITIAL_STATE'
};
